/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmployeesRouteImport } from './routes/employees'
import { Route as ExecutiveRouteImport } from './routes/executive'
import { Route as ItRouteImport } from './routes/it'
import { Route as ManagersRouteImport } from './routes/managers'
import { Route as ExecutiveIndexRouteImport } from './routes/executive.index'
import { Route as ExecutiveApprovalsRouteImport } from './routes/executive.approvals'
import { Route as ExecutiveDecisionsRouteImport } from './routes/executive.decisions'
import { Route as ExecutiveFinanceRouteImport } from './routes/executive.finance'
import { Route as ExecutiveProjectsRouteImport } from './routes/executive.projects'
import { Route as ExecutiveRelationshipsRouteImport } from './routes/executive.relationships'
import { Route as ExecutiveTasksRouteImport } from './routes/executive.tasks'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesRoute = EmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutiveRoute = ExecutiveRouteImport.update({
  id: '/executive',
  path: '/executive',
  getParentRoute: () => rootRouteImport,
} as any)
const ItRoute = ItRouteImport.update({
  id: '/it',
  path: '/it',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagersRoute = ManagersRouteImport.update({
  id: '/managers',
  path: '/managers',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutiveIndexRoute = ExecutiveIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExecutiveRoute,
} as any)
const ExecutiveApprovalsRoute = ExecutiveApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => ExecutiveRoute,
} as any)
const ExecutiveDecisionsRoute = ExecutiveDecisionsRouteImport.update({
  id: '/decisions',
  path: '/decisions',
  getParentRoute: () => ExecutiveRoute,
} as any)
const ExecutiveFinanceRoute = ExecutiveFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => ExecutiveRoute,
} as any)
const ExecutiveProjectsRoute = ExecutiveProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => ExecutiveRoute,
} as any)
const ExecutiveRelationshipsRoute = ExecutiveRelationshipsRouteImport.update({
  id: '/relationships',
  path: '/relationships',
  getParentRoute: () => ExecutiveRoute,
} as any)
const ExecutiveTasksRoute = ExecutiveTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => ExecutiveRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/employees': typeof EmployeesRoute
  '/executive': typeof ExecutiveRouteWithChildren
  '/it': typeof ItRoute
  '/managers': typeof ManagersRoute
  '/executive/approvals': typeof ExecutiveApprovalsRoute
  '/executive/decisions': typeof ExecutiveDecisionsRoute
  '/executive/finance': typeof ExecutiveFinanceRoute
  '/executive/projects': typeof ExecutiveProjectsRoute
  '/executive/relationships': typeof ExecutiveRelationshipsRoute
  '/executive/tasks': typeof ExecutiveTasksRoute
  '/executive/': typeof ExecutiveIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/employees': typeof EmployeesRoute
  '/it': typeof ItRoute
  '/managers': typeof ManagersRoute
  '/executive/approvals': typeof ExecutiveApprovalsRoute
  '/executive/decisions': typeof ExecutiveDecisionsRoute
  '/executive/finance': typeof ExecutiveFinanceRoute
  '/executive/projects': typeof ExecutiveProjectsRoute
  '/executive/relationships': typeof ExecutiveRelationshipsRoute
  '/executive/tasks': typeof ExecutiveTasksRoute
  '/executive': typeof ExecutiveIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/employees': typeof EmployeesRoute
  '/executive': typeof ExecutiveRouteWithChildren
  '/it': typeof ItRoute
  '/managers': typeof ManagersRoute
  '/executive/approvals': typeof ExecutiveApprovalsRoute
  '/executive/decisions': typeof ExecutiveDecisionsRoute
  '/executive/finance': typeof ExecutiveFinanceRoute
  '/executive/projects': typeof ExecutiveProjectsRoute
  '/executive/relationships': typeof ExecutiveRelationshipsRoute
  '/executive/tasks': typeof ExecutiveTasksRoute
  '/executive/': typeof ExecutiveIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/employees'
    | '/executive'
    | '/it'
    | '/managers'
    | '/executive/approvals'
    | '/executive/decisions'
    | '/executive/finance'
    | '/executive/projects'
    | '/executive/relationships'
    | '/executive/tasks'
    | '/executive/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/employees'
    | '/it'
    | '/managers'
    | '/executive/approvals'
    | '/executive/decisions'
    | '/executive/finance'
    | '/executive/projects'
    | '/executive/relationships'
    | '/executive/tasks'
    | '/executive'
  id:
    | '__root__'
    | '/'
    | '/employees'
    | '/executive'
    | '/it'
    | '/managers'
    | '/executive/approvals'
    | '/executive/decisions'
    | '/executive/finance'
    | '/executive/projects'
    | '/executive/relationships'
    | '/executive/tasks'
    | '/executive/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EmployeesRoute: typeof EmployeesRoute
  ExecutiveRoute: typeof ExecutiveRouteWithChildren
  ItRoute: typeof ItRoute
  ManagersRoute: typeof ManagersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees': {
      id: '/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof EmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/executive': {
      id: '/executive'
      path: '/executive'
      fullPath: '/executive'
      preLoaderRoute: typeof ExecutiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/it': {
      id: '/it'
      path: '/it'
      fullPath: '/it'
      preLoaderRoute: typeof ItRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/managers': {
      id: '/managers'
      path: '/managers'
      fullPath: '/managers'
      preLoaderRoute: typeof ManagersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/executive/': {
      id: '/executive/'
      path: '/'
      fullPath: '/executive/'
      preLoaderRoute: typeof ExecutiveIndexRouteImport
      parentRoute: typeof ExecutiveRoute
    }
    '/executive/approvals': {
      id: '/executive/approvals'
      path: '/approvals'
      fullPath: '/executive/approvals'
      preLoaderRoute: typeof ExecutiveApprovalsRouteImport
      parentRoute: typeof ExecutiveRoute
    }
    '/executive/decisions': {
      id: '/executive/decisions'
      path: '/decisions'
      fullPath: '/executive/decisions'
      preLoaderRoute: typeof ExecutiveDecisionsRouteImport
      parentRoute: typeof ExecutiveRoute
    }
    '/executive/finance': {
      id: '/executive/finance'
      path: '/finance'
      fullPath: '/executive/finance'
      preLoaderRoute: typeof ExecutiveFinanceRouteImport
      parentRoute: typeof ExecutiveRoute
    }
    '/executive/projects': {
      id: '/executive/projects'
      path: '/projects'
      fullPath: '/executive/projects'
      preLoaderRoute: typeof ExecutiveProjectsRouteImport
      parentRoute: typeof ExecutiveRoute
    }
    '/executive/relationships': {
      id: '/executive/relationships'
      path: '/relationships'
      fullPath: '/executive/relationships'
      preLoaderRoute: typeof ExecutiveRelationshipsRouteImport
      parentRoute: typeof ExecutiveRoute
    }
    '/executive/tasks': {
      id: '/executive/tasks'
      path: '/tasks'
      fullPath: '/executive/tasks'
      preLoaderRoute: typeof ExecutiveTasksRouteImport
      parentRoute: typeof ExecutiveRoute
    }
  }
}

interface ExecutiveRouteChildren {
  ExecutiveApprovalsRoute: typeof ExecutiveApprovalsRoute
  ExecutiveDecisionsRoute: typeof ExecutiveDecisionsRoute
  ExecutiveFinanceRoute: typeof ExecutiveFinanceRoute
  ExecutiveProjectsRoute: typeof ExecutiveProjectsRoute
  ExecutiveRelationshipsRoute: typeof ExecutiveRelationshipsRoute
  ExecutiveTasksRoute: typeof ExecutiveTasksRoute
  ExecutiveIndexRoute: typeof ExecutiveIndexRoute
}

const ExecutiveRouteChildren: ExecutiveRouteChildren = {
  ExecutiveApprovalsRoute: ExecutiveApprovalsRoute,
  ExecutiveDecisionsRoute: ExecutiveDecisionsRoute,
  ExecutiveFinanceRoute: ExecutiveFinanceRoute,
  ExecutiveProjectsRoute: ExecutiveProjectsRoute,
  ExecutiveRelationshipsRoute: ExecutiveRelationshipsRoute,
  ExecutiveTasksRoute: ExecutiveTasksRoute,
  ExecutiveIndexRoute: ExecutiveIndexRoute,
}

const ExecutiveRouteWithChildren = ExecutiveRoute._addFileChildren(
  ExecutiveRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EmployeesRoute: EmployeesRoute,
  ExecutiveRoute: ExecutiveRouteWithChildren,
  ItRoute: ItRoute,
  ManagersRoute: ManagersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
